drop table if exists default.szy_djte_dz_model_user_list_tot_var;
create table default.szy_djte_dz_model_user_list_tot_var as 
select aa.uid
      ,aa.flag
      ,aa.ato_tim
      ,aa.adt_tim
      ,aa.fst_ord_tim
      ,aa.lon_adt_dif
      ,aa.is_lon
      ,aa.is_0d_lon
      ,aa.is_7d_lon
      ,aa.is_15d_lon
      ,aa.is_30d_lon
      ,aa.is_90d_lon
      ,aa.is_180d_lon
      ,bb.bsc_cus_nat -- 民族
      ,bb.bsc_prv -- 定位省份
      ,bb.bsc_cty -- 定位城市
      ,bb.bsc_mrd -- 定位纬度
      ,bb.bsc_prl -- 定位经度
      ,bb.bsc_usr_acd --学历
      ,bb.bsc_mrg_flg -- 婚姻
      ,bb.bsc_sex_typ -- 性别
      ,bb.bsc_age_val -- 年龄
      ,bb.bsc_cre_lmt -- 自填卡额度
      ,bb.bsc_eml_typ -- 邮箱类别 正则调整
      ,bb.bsc_len_qq_num -- qq邮箱长度
      ,bb.bsc_avg_mth_icm -- 平均月收入
      ,bb.bsc_grd_yer -- 毕业年份
      ,bb.bsc_use_of_lon -- 借款用途
      ,bb.bsc_usr_crd_typ -- 绑卡类型
      ,bb.bsc_crd_mth_csp -- 信用卡月消费
      ,bb.bsc_yys_opt -- 运营商类型
      ,bb.bsc_cus_cha -- 用户渠道
      ,bb.bsc_is_cts --身份证地址是否农村
      ,bb.bsc_mob_cty -- 前七位伪表匹配 手机归属城市
      ,bb.bsc_mob_prv -- 前七位伪表匹配 手机归属省份
      ,bb.sns_ctt_cnt -- 通讯录中的敏感词个数
      ,bb.rel_cnt -- 通讯录个数  
      ,cc.tnd_rsk_itm_max_ptf_cnt -- 最大平台数
      ,cc.tnd_rsk_itm_psn_inf_chk -- 组别为个人基本信息核查的命中个数
      ,cc.tnd_rsk_itm_bhv_chk -- 组别为客户行为检测的命中个数
      ,cc.tnd_rsk_itm_rsk_chk -- 组别为风险信息扫描的命中个数
      ,cc.tnd_rsk_itm_bad_inf_chk -- 组别为不良信息扫描的命中个数
      ,cc.tnd_rsk_itm_mul_ptf_apl_chk -- 组别为多平台借贷申请检测的命中个数
      ,cc.tnd_rsk_itm_d7_gen_ist_ptf -- 七天内在一般消费分期平台申请的平台数
      ,cc.tnd_rsk_itm_d7_big_dat_fin -- 七天内在大数据金融平台申请的平台数
      ,cc.tnd_rsk_itm_d7_ptt_lon_cmp -- 七天内在小额贷款公司申请的平台数
      ,cc.tnd_rsk_itm_d7_p2p -- 七天内在P2P网贷申请的平台数
      ,cc.tnd_rsk_itm_d7_big_csm_fin_cmp -- 七天内在大型消费金融公司申请的平台数
      ,cc.tnd_rsk_itm_d7_crd_ctr -- 七天内在信用卡中心申请的平台数
      ,cc.tnd_rsk_itm_d7_fin_net -- 七天内在互联网金融门户申请的平台数
      ,cc.tnd_rsk_itm_d7_com_ecm_ptf -- 七天内在综合类电商平台申请的平台数
      ,cc.tnd_rsk_itm_d7_psn_bnk -- 七天内在银行个人业务申请的平台数
      ,cc.tnd_rsk_itm_d7_bnk_sml_lon -- 七天内在银行小微贷款平台申请的平台数
      ,cc.tnd_rsk_itm_d7_o2o -- 七天内在O2O平台申请的平台数
      ,cc.tnd_rsk_itm_d7_onl_bnk -- 七天内在网上银行申请的平台数
      ,cc.tnd_rsk_itm_d7_car_mnu_fin -- 七天内在厂商汽车金融平台申请的平台数
      ,cc.tnd_rsk_itm_d7_drt_sel_bnk -- 七天内在直销银行申请的平台数
      ,cc.tnd_rsk_itm_d7_rtl_bnk -- 七天内在银行消费金融公司申请的平台数
      ,cc.tnd_rsk_itm_d7_ppt_ins -- 七天内在财产保险平台申请的平台数
      ,cc.tnd_rsk_itm_d7_fin_les -- 七天内在融资租赁平台申请的平台数
      ,cc.tnd_rsk_itm_d7_eqp_les -- 七天内在设备租赁平台申请的平台数
      ,cc.tnd_rsk_itm_d7_thd_pty_svc_pvd -- 七天内在第三方服务商申请的平台数
      ,cc.tnd_rsk_itm_d7_hse_les -- 七天内在房屋租赁平台申请的平台数
      ,cc.tnd_rsk_itm_d7_grt -- 七天内在担保平台申请的平台数
      ,cc.tnd_rsk_itm_d7_fin_itt -- 七天内在理财机构申请的平台数
      ,cc.tnd_rsk_itm_d7_car_les -- 七天内在汽车租赁平台申请的平台数
      ,cc.tnd_rsk_itm_d7_inf_agt -- 七天内在信息中介申请的平台数
      ,cc.tnd_rsk_itm_d7_thd_pty_pay -- 七天内在第三方支付平台申请的平台数
      ,cc.tnd_rsk_itm_d7_rel_est_fin -- 七天内在房地产金融平台申请的平台数
      ,cc.tnd_rsk_itm_d7_vtc_ecm_ptf -- 七天内在垂直类电商平台申请的平台数
      ,cc.tnd_rsk_itm_d7_trp_les -- 七天内在交通工具租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m1_gen_ist_ptf -- 一个月内在一般消费分期平台申请的平台数
      ,cc.tnd_rsk_itm_m1_big_dat_fin -- 一个月内在大数据金融平台申请的平台数
      ,cc.tnd_rsk_itm_m1_ptt_lon_cmp -- 一个月内在小额贷款公司申请的平台数
      ,cc.tnd_rsk_itm_m1_p2p -- 一个月内在P2P网贷申请的平台数
      ,cc.tnd_rsk_itm_m1_big_csm_fin_cmp -- 一个月内在大型消费金融公司申请的平台数
      ,cc.tnd_rsk_itm_m1_crd_ctr -- 一个月内在信用卡中心申请的平台数
      ,cc.tnd_rsk_itm_m1_fin_net -- 一个月内在互联网金融门户申请的平台数
      ,cc.tnd_rsk_itm_m1_com_ecm_ptf -- 一个月内在综合类电商平台申请的平台数
      ,cc.tnd_rsk_itm_m1_psn_bnk -- 一个月内在银行个人业务申请的平台数
      ,cc.tnd_rsk_itm_m1_bnk_sml_lon -- 一个月内在银行小微贷款平台申请的平台数
      ,cc.tnd_rsk_itm_m1_o2o -- 一个月内在O2O平台申请的平台数
      ,cc.tnd_rsk_itm_m1_onl_bnk -- 一个月内在网上银行申请的平台数
      ,cc.tnd_rsk_itm_m1_car_mnu_fin -- 一个月内在厂商汽车金融平台申请的平台数
      ,cc.tnd_rsk_itm_m1_drt_sel_bnk -- 一个月内在直销银行申请的平台数
      ,cc.tnd_rsk_itm_m1_rtl_bnk -- 一个月内在银行消费金融公司申请的平台数
      ,cc.tnd_rsk_itm_m1_ppt_ins -- 一个月内在财产保险平台申请的平台数
      ,cc.tnd_rsk_itm_m1_fin_les -- 一个月内在融资租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m1_eqp_les -- 一个月内在设备租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m1_thd_pty_svc_pvd -- 一个月内在第三方服务商申请的平台数
      ,cc.tnd_rsk_itm_m1_hse_les -- 一个月内在房屋租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m1_grt -- 一个月内在担保平台申请的平台数
      ,cc.tnd_rsk_itm_m1_fin_itt -- 一个月内在理财机构申请的平台数
      ,cc.tnd_rsk_itm_m1_car_les -- 一个月内在汽车租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m1_inf_agt -- 一个月内在信息中介申请的平台数
      ,cc.tnd_rsk_itm_m1_thd_pty_pay -- 一个月内在第三方支付平台申请的平台数
      ,cc.tnd_rsk_itm_m1_rel_est_fin -- 一个月内在房地产金融平台申请的平台数
      ,cc.tnd_rsk_itm_m1_vtc_ecm_ptf -- 一个月内在垂直类电商平台申请的平台数
      ,cc.tnd_rsk_itm_m1_trp_les -- 一个月内在交通工具租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m3_gen_ist_ptf -- 三个月内在一般消费分期平台申请的平台数
      ,cc.tnd_rsk_itm_m3_big_dat_fin -- 三个月内在大数据金融平台申请的平台数
      ,cc.tnd_rsk_itm_m3_ptt_lon_cmp -- 三个月内在小额贷款公司申请的平台数
      ,cc.tnd_rsk_itm_m3_p2p -- 三个月内在P2P网贷申请的平台数
      ,cc.tnd_rsk_itm_m3_big_csm_fin_cmp -- 三个月内在大型消费金融公司申请的平台数
      ,cc.tnd_rsk_itm_m3_crd_ctr -- 三个月内在信用卡中心申请的平台数
      ,cc.tnd_rsk_itm_m3_fin_net -- 三个月内在互联网金融门户申请的平台数
      ,cc.tnd_rsk_itm_m3_com_ecm_ptf -- 三个月内在综合类电商平台申请的平台数
      ,cc.tnd_rsk_itm_m3_psn_bnk -- 三个月内在银行个人业务申请的平台数
      ,cc.tnd_rsk_itm_m3_bnk_sml_lon -- 三个月内在银行小微贷款平台申请的平台数
      ,cc.tnd_rsk_itm_m3_o2o -- 三个月内在O2O平台申请的平台数
      ,cc.tnd_rsk_itm_m3_onl_bnk -- 三个月内在网上银行申请的平台数
      ,cc.tnd_rsk_itm_m3_car_mnu_fin -- 三个月内在厂商汽车金融平台申请的平台数
      ,cc.tnd_rsk_itm_m3_drt_sel_bnk -- 三个月内在直销银行申请的平台数
      ,cc.tnd_rsk_itm_m3_rtl_bnk -- 三个月内在银行消费金融公司申请的平台数
      ,cc.tnd_rsk_itm_m3_ppt_ins -- 三个月内在财产保险平台申请的平台数
      ,cc.tnd_rsk_itm_m3_fin_les -- 三个月内在融资租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m3_eqp_les -- 三个月内在设备租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m3_thd_pty_svc_pvd -- 三个月内在第三方服务商申请的平台数
      ,cc.tnd_rsk_itm_m3_hse_les -- 三个月内在房屋租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m3_grt -- 三个月内在担保平台申请的平台数
      ,cc.tnd_rsk_itm_m3_fin_itt -- 三个月内在理财机构申请的平台数
      ,cc.tnd_rsk_itm_m3_car_les -- 三个月内在汽车租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m3_inf_agt -- 三个月内在信息中介申请的平台数
      ,cc.tnd_rsk_itm_m3_thd_pty_pay -- 三个月内在第三方支付平台申请的平台数
      ,cc.tnd_rsk_itm_m3_rel_est_fin -- 三个月内在房地产金融平台申请的平台数
      ,cc.tnd_rsk_itm_m3_vtc_ecm_ptf -- 三个月内在垂直类电商平台申请的平台数
      ,cc.tnd_rsk_itm_m3_trp_les -- 三个月内在交通工具租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m6_gen_ist_ptf -- 六个月内在一般消费分期平台申请的平台数
      ,cc.tnd_rsk_itm_m6_big_dat_fin -- 六个月内在大数据金融平台申请的平台数
      ,cc.tnd_rsk_itm_m6_ptt_lon_cmp -- 六个月内在小额贷款公司申请的平台数
      ,cc.tnd_rsk_itm_m6_p2p -- 六个月内在P2P网贷申请的平台数
      ,cc.tnd_rsk_itm_m6_big_csm_fin_cmp -- 六个月内在大型消费金融公司申请的平台数
      ,cc.tnd_rsk_itm_m6_crd_ctr -- 六个月内在信用卡中心申请的平台数
      ,cc.tnd_rsk_itm_m6_fin_net -- 六个月内在互联网金融门户申请的平台数
      ,cc.tnd_rsk_itm_m6_com_ecm_ptf -- 六个月内在综合类电商平台申请的平台数
      ,cc.tnd_rsk_itm_m6_psn_bnk -- 六个月内在银行个人业务申请的平台数
      ,cc.tnd_rsk_itm_m6_bnk_sml_lon -- 六个月内在银行小微贷款平台申请的平台数
      ,cc.tnd_rsk_itm_m6_o2o -- 六个月内在O2O平台申请的平台数
      ,cc.tnd_rsk_itm_m6_onl_bnk -- 六个月内在网上银行申请的平台数
      ,cc.tnd_rsk_itm_m6_car_mnu_fin -- 六个月内在厂商汽车金融平台申请的平台数
      ,cc.tnd_rsk_itm_m6_drt_sel_bnk -- 六个月内在直销银行申请的平台数
      ,cc.tnd_rsk_itm_m6_rtl_bnk -- 六个月内在银行消费金融公司申请的平台数
      ,cc.tnd_rsk_itm_m6_ppt_ins -- 六个月内在财产保险平台申请的平台数
      ,cc.tnd_rsk_itm_m6_fin_les -- 六个月内在融资租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m6_eqp_les -- 六个月内在设备租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m6_thd_pty_svc_pvd -- 六个月内在第三方服务商申请的平台数
      ,cc.tnd_rsk_itm_m6_hse_les -- 六个月内在房屋租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m6_grt -- 六个月内在担保平台申请的平台数
      ,cc.tnd_rsk_itm_m6_fin_itt -- 六个月内在理财机构申请的平台数
      ,cc.tnd_rsk_itm_m6_car_les -- 六个月内在汽车租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m6_inf_agt -- 六个月内在信息中介申请的平台数
      ,cc.tnd_rsk_itm_m6_thd_pty_pay -- 六个月内在第三方支付平台申请的平台数
      ,cc.tnd_rsk_itm_m6_rel_est_fin -- 六个月内在房地产金融平台申请的平台数
      ,cc.tnd_rsk_itm_m6_vtc_ecm_ptf -- 六个月内在垂直类电商平台申请的平台数
      ,cc.tnd_rsk_itm_m6_trp_les -- 六个月内在交通工具租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m12_gen_ist_ptf -- 一年内在一般消费分期平台申请的平台数
      ,cc.tnd_rsk_itm_m12_big_dat_fin -- 一年内在大数据金融平台申请的平台数
      ,cc.tnd_rsk_itm_m12_ptt_lon_cmp -- 一年内在小额贷款公司申请的平台数
      ,cc.tnd_rsk_itm_m12_p2p -- 一年内在P2P网贷申请的平台数
      ,cc.tnd_rsk_itm_m12_big_csm_fin_cmp -- 一年内在大型消费金融公司申请的平台数
      ,cc.tnd_rsk_itm_m12_crd_ctr -- 一年内在信用卡中心申请的平台数
      ,cc.tnd_rsk_itm_m12_fin_net -- 一年内在互联网金融门户申请的平台数
      ,cc.tnd_rsk_itm_m12_com_ecm_ptf -- 一年内在综合类电商平台申请的平台数
      ,cc.tnd_rsk_itm_m12_psn_bnk -- 一年内在银行个人业务申请的平台数
      ,cc.tnd_rsk_itm_m12_bnk_sml_lon -- 一年内在银行小微贷款平台申请的平台数
      ,cc.tnd_rsk_itm_m12_o2o -- 一年内在O2O平台申请的平台数
      ,cc.tnd_rsk_itm_m12_onl_bnk -- 一年内在网上银行申请的平台数
      ,cc.tnd_rsk_itm_m12_car_mnu_fin -- 一年内在厂商汽车金融平台申请的平台数
      ,cc.tnd_rsk_itm_m12_drt_sel_bnk -- 一年内在直销银行申请的平台数
      ,cc.tnd_rsk_itm_m12_rtl_bnk -- 一年内在银行消费金融公司申请的平台数
      ,cc.tnd_rsk_itm_m12_ppt_ins -- 一年内在财产保险平台申请的平台数
      ,cc.tnd_rsk_itm_m12_fin_les -- 一年内在融资租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m12_eqp_les -- 一年内在设备租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m12_thd_pty_svc_pvd -- 一年内在第三方服务商申请的平台数
      ,cc.tnd_rsk_itm_m12_hse_les -- 一年内在房屋租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m12_grt -- 一年内在担保平台申请的平台数
      ,cc.tnd_rsk_itm_m12_fin_itt -- 一年内在理财机构申请的平台数
      ,cc.tnd_rsk_itm_m12_car_les -- 一年内在汽车租赁平台申请的平台数
      ,cc.tnd_rsk_itm_m12_inf_agt -- 一年内在信息中介申请的平台数
      ,cc.tnd_rsk_itm_m12_thd_pty_pay -- 一年内在第三方支付平台申请的平台数
      ,cc.tnd_rsk_itm_m12_rel_est_fin -- 一年内在房地产金融平台申请的平台数
      ,cc.tnd_rsk_itm_m12_vtc_ecm_ptf -- 一年内在垂直类电商平台申请的平台数
      ,cc.tnd_rsk_itm_m12_trp_les -- 一年内在交通工具租赁平台申请的平台数
      ,cc.tnd_rsk_itm_7d_div_1m -- （7天/1个月）的申请人在多个平台申请借款的平台数
      ,cc.tnd_rsk_itm_7d_div_3m -- （7天/3个月）的申请人在多个平台申请借款的平台数
      ,cc.tnd_rsk_itm_7d_div_6m -- （7天/6个月）的申请人在多个平台申请借款的平台数
      ,cc.tnd_rsk_itm_7d_div_12m -- （7天/12个月）的申请人在多个平台申请借款的平台数
      ,cc.tnd_rsk_itm_1m_div_3m -- （1个月/3个月）的申请人在多个平台申请借款的平台数
      ,cc.tnd_rsk_itm_1m_div_6m -- （1个月/6个月）的申请人在多个平台申请借款的平台数
      ,cc.tnd_rsk_itm_1m_div_12m -- （1个月/12个月）的申请人在多个平台申请借款的平台数
      ,cc.tnd_rsk_itm_3m_div_6m -- （3个月/6个月）的申请人在多个平台申请借款的平台数
      ,cc.tnd_rsk_itm_3m_div_12m -- （3个月/12个月）的申请人在多个平台申请借款的平台数
      ,cc.tnd_rsk_itm_6m_div_12m -- （6个月/12个月）的申请人在多个平台申请借款的平台数
      ,cc.tnd_rsk_itm_1m_dif_7d -- （1个月-7天）的申请人在多个平台申请借款的平台数
      ,cc.tnd_rsk_itm_3m_dif_1m -- （3个月-1个月）的申请人在多个平台申请借款的平台数
      ,cc.tnd_rsk_itm_6m_dif_3m -- （6个月-3个月）的申请人在多个平台申请借款的平台数
      ,cc.tnd_rsk_itm_12m_dif_6m -- （12个月-6个月）的申请人在多个平台申请借款的平台数
      ,cc.tnd_rsk_itm_rsk_mid_div -- 命中中风险次数占三个风险级别总次数的比例
      ,cc.tnd_rsk_itm_rsk_hgh_div -- 命中高风险次数占三个风险级别总次数的比例
      ,cc.tnd_rsk_itm_rsk_low_div -- 命中低风险次数占三个风险级别总次数的比例
      ,cc.tnd_rsk_itm_d7_les -- 七天内在租赁平台合集申请的平台数
      ,cc.tnd_rsk_itm_d7_bnk -- 七天内在银行合集申请的平台数
      ,cc.tnd_rsk_itm_d7_csm -- 七天内在持牌消金合集申请的平台数
      ,cc.tnd_rsk_itm_d7_ecm_ptf -- 七天内在电商合集申请的平台数
      ,cc.tnd_rsk_itm_d7_ptt_lon -- 七天内在小微贷款合集申请的平台数
      ,cc.tnd_rsk_itm_d7_oth -- 七天内在其他合集申请的平台数
      ,cc.tnd_rsk_itm_m1_les -- 一个月内在租赁平台合集申请的平台数
      ,cc.tnd_rsk_itm_m1_bnk -- 一个月内在银行合集申请的平台数
      ,cc.tnd_rsk_itm_m1_csm -- 一个月内在持牌消金合集申请的平台数
      ,cc.tnd_rsk_itm_m1_ecm_ptf -- 一个月内在电商合集申请的平台数
      ,cc.tnd_rsk_itm_m1_ptt_lon -- 一个月内在小微贷款合集申请的平台数
      ,cc.tnd_rsk_itm_m1_oth -- 一个月内在其他合集申请的平台数
      ,cc.tnd_rsk_itm_m3_les -- 三个月内在租赁平台合集申请的平台数
      ,cc.tnd_rsk_itm_m3_bnk -- 三个月内在银行合集申请的平台数
      ,cc.tnd_rsk_itm_m3_csm -- 三个月内在持牌消金合集申请的平台数
      ,cc.tnd_rsk_itm_m3_ecm_ptf -- 三个月内在电商合集申请的平台数
      ,cc.tnd_rsk_itm_m3_ptt_lon -- 三个月内在小微贷款合集申请的平台数
      ,cc.tnd_rsk_itm_m3_oth -- 三个月内在其他合集申请的平台数
      ,cc.tnd_rsk_itm_m6_les -- 六个月内在租赁平台合集申请的平台数
      ,cc.tnd_rsk_itm_m6_bnk -- 六个月内在银行合集申请的平台数
      ,cc.tnd_rsk_itm_m6_csm -- 六个月内在持牌消金合集申请的平台数
      ,cc.tnd_rsk_itm_m6_ecm_ptf -- 六个月内在电商合集申请的平台数
      ,cc.tnd_rsk_itm_m6_ptt_lon -- 六个月内在小微贷款合集申请的平台数
      ,cc.tnd_rsk_itm_m6_oth -- 六个月内在其他合集申请的平台数
      ,cc.tnd_rsk_itm_m12_les -- 十二个月内在租赁平台合集申请的平台数
      ,cc.tnd_rsk_itm_m12_bnk -- 十二个月内在银行合集申请的平台数
      ,cc.tnd_rsk_itm_m12_csm -- 十二个月内在持牌消金合集申请的平台数
      ,cc.tnd_rsk_itm_m12_ecm_ptf -- 十二个月内在电商合集申请的平台数
      ,cc.tnd_rsk_itm_m12_ptt_lon -- 十二个月内在小微贷款合集申请的平台数	
      ,cc.tnd_rsk_itm_m12_oth -- 十二个月内在其他合集申请的平台数
      ,cc.tnd_rsk_itm_d7_les_rat -- 七天内在租赁平台合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_d7_bnk_rat -- 七天内在银行合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_d7_csm_rat -- 七天内在持牌消金合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_d7_car_rat -- 七天内在汽车合集申请的平台数/总平台次数
      ,cc.tnd_rsk_itm_d7_ecm_ptf_rat -- 七天内在电商合集的申请次数/总平台数
      ,cc.tnd_rsk_itm_d7_ptt_lon_rat -- 七天内在小微贷款合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_d7_oth_rat -- 七天内在其他合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m1_les_rat -- 一个月内在租赁平台合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m1_bnk_rat -- 一个月内在银行合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m1_csm_rat -- 一个月内在持牌消金合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m1_car_rat -- 一个月内在汽车合集申请的平台数/总平台次数
      ,cc.tnd_rsk_itm_m1_ecm_ptf_rat -- 一个月内在电商合集的申请次数/总平台数
      ,cc.tnd_rsk_itm_m1_ptt_lon_rat -- 一个月内在小微贷款合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m1_oth_rat -- 一个月内在其他合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m3_les_rat -- 三个月内在租赁平台合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m3_bnk_rat -- 三个月内在银行合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m3_csm_rat -- 三个月内在持牌消金合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m3_car_rat -- 三个月内在汽车合集申请的平台数/总平台次数
      ,cc.tnd_rsk_itm_m3_ecm_ptf_rat -- 三个月内在电商合集的申请次数/总平台数
      ,cc.tnd_rsk_itm_m3_ptt_lon_rat -- 三个月内在小微贷款合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m3_oth_rat -- 三个月内在其他合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m6_les_rat -- 六个月内在租赁平台合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m6_bnk_rat -- 六个月内在银行合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m6_csm_rat -- 六个月内在持牌消金合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m6_car_rat -- 六个月内在汽车合集申请的平台数/总平台次数
      ,cc.tnd_rsk_itm_m6_ecm_ptf_rat -- 六个月内在电商合集的申请次数/总平台数
      ,cc.tnd_rsk_itm_m6_ptt_lon_rat -- 六个月内在小微贷款合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m6_oth_rat -- 六个月内在其他合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m12_les_rat -- 十二个月内在租赁平台合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m12_bnk_rat -- 十二个月内在银行合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m12_csm_rat -- 十二个月内在持牌消金合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m12_car_rat -- 十二个月内在汽车合集申请的平台数/总平台次数
      ,cc.tnd_rsk_itm_m12_ecm_ptf_rat -- 十二个月内在电商合集的申请次数/总平台数
      ,cc.tnd_rsk_itm_m12_ptt_lon_rat -- 十二个月内在小微贷款合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_m12_oth_rat -- 十二个月内在其他合集申请的平台数/总平台数
      ,cc.tnd_rsk_itm_d7_typ -- 7天内申请人在多个平台申请借款的平台类别数
      ,cc.tnd_rsk_itm_m1_typ -- 1个月内申请人在多个平台申请借款的平台类别数
      ,cc.tnd_rsk_itm_m3_typ -- 3个月内申请人在多个平台申请借款的平台类别数
      ,cc.tnd_rsk_itm_m6_typ -- 6个月内申请人在多个平台申请借款的平台类别数
      ,cc.tnd_rsk_itm_m12_typ -- 12个月内申请人在多个平台申请借款的平台类别数
      ,cc.tnd_rsk_itm_typ_7d_div_m12 -- （7天/12个月）的申请人在多个平台申请借款的平台类别数
      ,cc.tnd_rsk_itm_typ_m1_div_m12 -- （1个月/12个月）的申请人在多个平台申请借款的平台类别数
      ,cc.tnd_rsk_itm_typ_m3_div_m12 -- （3个月/12个月）的申请人在多个平台申请借款的平台类别数
      ,cc.tnd_rsk_itm_typ_m6_div_m12 -- （6个月/12个月）的申请人在多个平台申请借款的平台类别数
      ,cc.tnd_rsk_itm_typ_d7_div_m6 -- （7天/6个月）的申请人在多个平台申请借款的平台类别数
      ,cc.tnd_rsk_itm_typ_m1_div_m6 -- （1个月/6个月）的申请人在多个平台申请借款的平台类别数
      ,cc.tnd_rsk_itm_typ_m3_div_m6 -- （3个月/6个月）的申请人在多个平台申请借款的平台类别数
      ,cc.tnd_rsk_itm_typ_d7_div_m3 -- （7天/3个月）的申请人在多个平台申请借款的平台类别数
      ,cc.tnd_rsk_itm_typ_m1_div_m3 -- （1个月/3个月）的申请人在多个平台申请借款的平台类别数
      ,cc.tnd_rsk_itm_typ_d7_div_m1 -- （7天/1个月）的申请人在多个平台申请借款的平台类别数
      ,dd.als_d7_pdl_allnum -- 按手机号和身份证查询较大值，近7天申请线上小额现金贷的次数
      ,dd.als_d7_pdl_orgnum -- 按手机号和身份证查询较大值，近7天申请线上小额现金贷的机构数
      ,dd.als_d7_caon_allnum -- 按手机号和身份证查询较大值，近7天申请线上现金分期的次数
      ,dd.als_d7_caon_orgnum -- 按手机号和身份证查询较大值，近7天申请线上现金分期的机构数
      ,dd.als_d7_rel_allnum -- 按手机号和身份证查询较大值，近7天申请信用卡（类信用卡）的次数
      ,dd.als_d7_rel_orgnum -- 按手机号和身份证查询较大值，近7天申请信用卡（类信用卡）的机构数
      ,dd.als_d7_caoff_allnum -- 按手机号和身份证查询较大值，近7天申请线下现金分期的次数
      ,dd.als_d7_caoff_orgnum -- 按手机号和身份证查询较大值，近7天申请线下现金分期的机构数
      ,dd.als_d7_cooff_allnum -- 按手机号和身份证查询较大值，近7天申请线下消费分期的次数
      ,dd.als_d7_cooff_orgnum -- 按手机号和身份证查询较大值，近7天申请线下消费分期的机构数
      ,dd.als_d7_af_allnum -- 按手机号和身份证查询较大值，近7天申请汽车金融的次数
      ,dd.als_d7_af_orgnum -- 按手机号和身份证查询较大值，近7天申请汽车金融的机构数
      ,dd.als_d7_coon_allnum -- 按手机号和身份证查询较大值，近7天申请线上消费分期的次数
      ,dd.als_d7_coon_orgnum -- 按手机号和身份证查询较大值，近7天申请线上消费分期的机构数
      ,dd.als_d7_oth_allnum -- 按手机号和身份证查询较大值，近7天申请其他的次数
      ,dd.als_d7_oth_orgnum -- 按手机号和身份证查询较大值，近7天申请其他的机构数
      ,dd.als_d7_bank_selfnum -- 按手机号和身份证查询较大值，近7天在本机构(本机构为银行)的申请次数
      ,dd.als_d7_bank_allnum -- 按手机号和身份证查询较大值，近7天在银行机构申请次数
      ,dd.als_d7_bank_tra_allnum -- 按手机号和身份证查询较大值，近7天在银行机构传统银行申请次数
      ,dd.als_d7_bank_ret_allnum -- 按手机号和身份证查询较大值，近7天在银行机构网络零售银行申请次数
      ,dd.als_d7_bank_orgnum -- 按手机号和身份证查询较大值，近7天在银行机构申请机构数
      ,dd.als_d7_bank_tra_orgnum -- 按手机号和身份证查询较大值，近7天在银行机构传统银行申请机构数
      ,dd.als_d7_bank_ret_orgnum -- 按手机号和身份证查询较大值，近7天在银行机构网络零售银行申请机构数
      ,dd.als_d7_bank_week_allnum -- 按手机号和身份证查询较大值，近7天在银行机构周末申请次数
      ,dd.als_d7_bank_week_orgnum -- 按手机号和身份证查询较大值，近7天在银行机构周末申请机构数
      ,dd.als_d7_bank_night_allnum -- 按手机号和身份证查询较大值，近7天在银行机构夜间申请次数
      ,dd.als_d7_bank_night_orgnum -- 按手机号和身份证查询较大值，近7天在银行机构夜间申请机构数
      ,dd.als_d7_nbank_selfnum -- 按手机号和身份证查询较大值，近7天在本机构(本机构为非银)申请次数
      ,dd.als_d7_nbank_allnum -- 按手机号和身份证查询较大值，近7天在非银机构申请次数
      ,dd.als_d7_nbank_p2p_allnum -- 按手机号和身份证查询较大值，近7天在非银机构p2p机构申请次数
      ,dd.als_d7_nbank_mc_allnum -- 按手机号和身份证查询较大值，近7天在非银机构小贷机构申请次数
      ,dd.als_d7_nbank_ca_allnum -- 按手机号和身份证查询较大值，近7天在非银机构现金类分期机构申请次数
      ,dd.als_d7_nbank_cf_allnum -- 按手机号和身份证查询较大值，近7天在非银机构消费类分期机构申请次数
      ,dd.als_d7_nbank_com_allnum -- 按手机号和身份证查询较大值，近7天在非银机构代偿类分期机构申请次数
      ,dd.als_d7_nbank_oth_allnum -- 按手机号和身份证查询较大值，近7天在非银机构其他申请次数
      ,dd.als_d7_nbank_nsloan_allnum -- 按手机号和身份证查询较大值，近7天在非银机构持牌网络小贷机构申请次数
      ,dd.als_d7_nbank_autofin_allnum -- 按手机号和身份证查询较大值，近7天在非银机构持牌汽车金融机构申请次数
      ,dd.als_d7_nbank_sloan_allnum -- 按手机号和身份证查询较大值，近7天在非银机构持牌小贷机构申请次数
      ,dd.als_d7_nbank_cons_allnum -- 按手机号和身份证查询较大值，近7天在非银机构持牌消费金融机构申请次数
      ,dd.als_d7_nbank_finlea_allnum -- 按手机号和身份证查询较大值，近7天在非银机构持牌融资租赁机构申请次数
      ,dd.als_d7_nbank_else_allnum -- 按手机号和身份证查询较大值，近7天在非银机构其他申请次数
      ,dd.als_d7_nbank_orgnum -- 按手机号和身份证查询较大值，近7天在非银机构申请机构数
      ,dd.als_d7_nbank_p2p_orgnum -- 按手机号和身份证查询较大值，近7天在非银机构p2p申请机构数
      ,dd.als_d7_nbank_mc_orgnum -- 按手机号和身份证查询较大值，近7天在非银机构小贷申请机构数
      ,dd.als_d7_nbank_ca_orgnum -- 按手机号和身份证查询较大值，近7天在非银机构现金类分期申请机构数
      ,dd.als_d7_nbank_cf_orgnum -- 按手机号和身份证查询较大值，近7天在非银机构消费类分期申请机构数
      ,dd.als_d7_nbank_com_orgnum -- 按手机号和身份证查询较大值，近7天在非银机构代偿类分期申请机构数
      ,dd.als_d7_nbank_oth_orgnum -- 按手机号和身份证查询较大值，近7天在非银机构其他申请机构数
      ,dd.als_d7_nbank_nsloan_orgnum -- 按手机号和身份证查询较大值，近7天在非银机构持牌网络小贷机构申请机构数
      ,dd.als_d7_nbank_autofin_orgnum -- 按手机号和身份证查询较大值，近7天在非银机构持牌汽车金融机构申请机构数
      ,dd.als_d7_nbank_sloan_orgnum -- 按手机号和身份证查询较大值，近7天在非银机构持牌小贷机构申请机构数
      ,dd.als_d7_nbank_cons_orgnum -- 按手机号和身份证查询较大值，近7天在非银机构持牌消费金融机构申请机构数
      ,dd.als_d7_nbank_finlea_orgnum -- 按手机号和身份证查询较大值，近7天在非银机构持牌消费金融机构申请机构数
      ,dd.als_d7_nbank_else_orgnum -- 按手机号和身份证查询较大值，近7天在非银机构其他申请机构数
      ,dd.als_d7_nbank_week_allnum -- 按手机号和身份证查询较大值，近7天在非银机构周末申请次数
      ,dd.als_d7_nbank_week_orgnum -- 按手机号和身份证查询较大值，近7天在非银机构周末申请机构数
      ,dd.als_d7_nbank_night_allnum -- 按手机号和身份证查询较大值，近7天在非银机构夜间申请次数
      ,dd.als_d7_nbank_night_orgnum -- 按手机号和身份证查询较大值，近7天在非银机构夜间申请机构数
      ,dd.als_d15_pdl_allnum -- 按手机号和身份证查询较大值，近15天申请线上小额现金贷的次数
      ,dd.als_d15_pdl_orgnum -- 按手机号和身份证查询较大值，近15天申请线上小额现金贷的机构数
      ,dd.als_d15_caon_allnum -- 按手机号和身份证查询较大值，近15天申请线上现金分期的次数
      ,dd.als_d15_caon_orgnum -- 按手机号和身份证查询较大值，近15天申请线上现金分期的机构数
      ,dd.als_d15_rel_allnum -- 按手机号和身份证查询较大值，近15天申请信用卡（类信用卡）的次数
      ,dd.als_d15_rel_orgnum -- 按手机号和身份证查询较大值，近15天申请信用卡（类信用卡）的机构数
      ,dd.als_d15_caoff_allnum -- 按手机号和身份证查询较大值，近15天申请线下现金分期的次数
      ,dd.als_d15_caoff_orgnum -- 按手机号和身份证查询较大值，近15天申请线下现金分期的机构数
      ,dd.als_d15_cooff_allnum -- 按手机号和身份证查询较大值，近15天申请线下消费分期的次数
      ,dd.als_d15_cooff_orgnum -- 按手机号和身份证查询较大值，近15天申请线下消费分期的机构数
      ,dd.als_d15_af_allnum -- 按手机号和身份证查询较大值，近15天申请汽车金融的次数
      ,dd.als_d15_af_orgnum -- 按手机号和身份证查询较大值，近15天申请汽车金融的机构数
      ,dd.als_d15_coon_allnum -- 按手机号和身份证查询较大值，近15天申请线上消费分期的次数
      ,dd.als_d15_coon_orgnum -- 按手机号和身份证查询较大值，近15天申请线上消费分期的机构数
      ,dd.als_d15_oth_allnum -- 按手机号和身份证查询较大值，近15天申请其他的次数
      ,dd.als_d15_oth_orgnum -- 按手机号和身份证查询较大值，近15天申请其他的机构数
      ,dd.als_d15_bank_selfnum -- 按手机号和身份证查询较大值，近15天在本机构(本机构为银行)的申请次数
      ,dd.als_d15_bank_allnum -- 按手机号和身份证查询较大值，近15天在银行机构申请次数
      ,dd.als_d15_bank_tra_allnum -- 按手机号和身份证查询较大值，近15天在银行机构传统银行申请次数
      ,dd.als_d15_bank_ret_allnum -- 按手机号和身份证查询较大值，近15天在银行机构网络零售银行申请次数
      ,dd.als_d15_bank_orgnum -- 按手机号和身份证查询较大值，近15天在银行机构申请机构数
      ,dd.als_d15_bank_tra_orgnum -- 按手机号和身份证查询较大值，近15天在银行机构传统银行申请机构数
      ,dd.als_d15_bank_ret_orgnum -- 按手机号和身份证查询较大值，近15天在银行机构网络零售银行申请机构数
      ,dd.als_d15_bank_week_allnum -- 按手机号和身份证查询较大值，近15天在银行机构周末申请次数
      ,dd.als_d15_bank_week_orgnum -- 按手机号和身份证查询较大值，近15天在银行机构周末申请机构数
      ,dd.als_d15_bank_night_allnum -- 按手机号和身份证查询较大值，近15天在银行机构夜间申请次数
      ,dd.als_d15_bank_night_orgnum -- 按手机号和身份证查询较大值，近15天在银行机构夜间申请机构数
      ,dd.als_d15_nbank_selfnum -- 按手机号和身份证查询较大值，近15天在本机构(本机构为非银)申请次数
      ,dd.als_d15_nbank_allnum -- 按手机号和身份证查询较大值，近15天在非银机构申请次数
      ,dd.als_d15_nbank_p2p_allnum -- 按手机号和身份证查询较大值，近15天在非银机构p2p机构申请次数
      ,dd.als_d15_nbank_mc_allnum -- 按手机号和身份证查询较大值，近15天在非银机构小贷机构申请次数
      ,dd.als_d15_nbank_ca_allnum -- 按手机号和身份证查询较大值，近15天在非银机构现金类分期机构申请次数
      ,dd.als_d15_nbank_cf_allnum -- 按手机号和身份证查询较大值，近15天在非银机构消费类分期机构申请次数
      ,dd.als_d15_nbank_com_allnum -- 按手机号和身份证查询较大值，近15天在非银机构代偿类分期机构申请次数
      ,dd.als_d15_nbank_oth_allnum -- 按手机号和身份证查询较大值，近15天在非银机构其他申请次数
      ,dd.als_d15_nbank_nsloan_allnum -- 按手机号和身份证查询较大值，近15天在非银机构持牌网络小贷机构申请次数
      ,dd.als_d15_nbank_autofin_allnum -- 按手机号和身份证查询较大值，近15天在非银机构持牌汽车金融机构申请次数
      ,dd.als_d15_nbank_sloan_allnum -- 按手机号和身份证查询较大值，近15天在非银机构持牌小贷机构申请次数
      ,dd.als_d15_nbank_cons_allnum -- 按手机号和身份证查询较大值，近15天在非银机构持牌消费金融机构申请次数
      ,dd.als_d15_nbank_finlea_allnum -- 按手机号和身份证查询较大值，近15天在非银机构持牌融资租赁机构申请次数
      ,dd.als_d15_nbank_else_allnum -- 按手机号和身份证查询较大值，近15天在非银机构其他申请次数
      ,dd.als_d15_nbank_orgnum -- 按手机号和身份证查询较大值，近15天在非银机构申请机构数
      ,dd.als_d15_nbank_p2p_orgnum -- 按手机号和身份证查询较大值，近15天在非银机构p2p申请机构数
      ,dd.als_d15_nbank_mc_orgnum -- 按手机号和身份证查询较大值，近15天在非银机构小贷申请机构数
      ,dd.als_d15_nbank_ca_orgnum -- 按手机号和身份证查询较大值，近15天在非银机构现金类分期申请机构数
      ,dd.als_d15_nbank_cf_orgnum -- 按手机号和身份证查询较大值，近15天在非银机构消费类分期申请机构数
      ,dd.als_d15_nbank_com_orgnum -- 按手机号和身份证查询较大值，近15天在非银机构代偿类分期申请机构数
      ,dd.als_d15_nbank_oth_orgnum -- 按手机号和身份证查询较大值，近15天在非银机构其他申请机构数
      ,dd.als_d15_nbank_nsloan_orgnum -- 按手机号和身份证查询较大值，近15天在非银机构持牌网络小贷机构申请机构数
      ,dd.als_d15_nbank_autofin_orgnum -- 按手机号和身份证查询较大值，近15天在非银机构持牌汽车金融机构申请机构数
      ,dd.als_d15_nbank_sloan_orgnum -- 按手机号和身份证查询较大值，近15天在非银机构持牌小贷机构申请机构数
      ,dd.als_d15_nbank_cons_orgnum -- 按手机号和身份证查询较大值，近15天在非银机构持牌消费金融机构申请机构数
      ,dd.als_d15_nbank_finlea_orgnum -- 按手机号和身份证查询较大值，近15天在非银机构持牌融资租赁机构申请机构数
      ,dd.als_d15_nbank_else_orgnum -- 按手机号和身份证查询较大值，近15天在非银机构其他申请机构数
      ,dd.als_d15_nbank_week_allnum -- 按手机号和身份证查询较大值，近15天在非银机构周末申请次数
      ,dd.als_d15_nbank_week_orgnum -- 按手机号和身份证查询较大值，近15天在非银机构周末申请机构数
      ,dd.als_d15_nbank_night_allnum -- 按手机号和身份证查询较大值，近15天在非银机构夜间申请次数
      ,dd.als_d15_nbank_night_orgnum -- 按手机号和身份证查询较大值，近15天在非银机构夜间申请机构数
      ,dd.als_m1_pdl_allnum -- 按手机号和身份证查询较大值，近1个月申请线上小额现金贷的次数
      ,dd.als_m1_pdl_orgnum -- 按手机号和身份证查询较大值，近1个月申请线上小额现金贷的机构数
      ,dd.als_m1_caon_allnum -- 按手机号和身份证查询较大值，近1个月申请线上现金分期的次数
      ,dd.als_m1_caon_orgnum -- 按手机号和身份证查询较大值，近1个月申请线上现金分期的机构数
      ,dd.als_m1_rel_allnum -- 按手机号和身份证查询较大值，近1个月申请信用卡（类信用卡）的次数
      ,dd.als_m1_rel_orgnum -- 按手机号和身份证查询较大值，近1个月申请信用卡（类信用卡）的机构数
      ,dd.als_m1_caoff_allnum -- 按手机号和身份证查询较大值，近1个月申请线下现金分期的次数
      ,dd.als_m1_caoff_orgnum -- 按手机号和身份证查询较大值，近1个月申请线下现金分期的机构数
      ,dd.als_m1_cooff_allnum -- 按手机号和身份证查询较大值，近1个月申请线下消费分期的次数
      ,dd.als_m1_cooff_orgnum -- 按手机号和身份证查询较大值，近1个月申请线下消费分期的机构数
      ,dd.als_m1_af_allnum -- 按手机号和身份证查询较大值，近1个月申请汽车金融的次数
      ,dd.als_m1_af_orgnum -- 按手机号和身份证查询较大值，近1个月申请汽车金融的机构数
      ,dd.als_m1_coon_allnum -- 按手机号和身份证查询较大值，近1个月申请线上消费分期的次数
      ,dd.als_m1_coon_orgnum -- 按手机号和身份证查询较大值，近1个月申请线上消费分期的机构数
      ,dd.als_m1_oth_allnum -- 按手机号和身份证查询较大值，近1个月申请其他的次数
      ,dd.als_m1_oth_orgnum -- 按手机号和身份证查询较大值，近1个月申请其他的机构数
      ,dd.als_m1_bank_selfnum -- 按手机号和身份证查询较大值，近1个月在本机构(本机构为银行)的申请次数
      ,dd.als_m1_bank_allnum -- 按手机号和身份证查询较大值，近1个月在银行机构申请次数
      ,dd.als_m1_bank_tra_allnum -- 按手机号和身份证查询较大值，近1个月在银行机构传统银行申请次数
      ,dd.als_m1_bank_ret_allnum -- 按手机号和身份证查询较大值，近1个月在银行机构网络零售银行申请次数
      ,dd.als_m1_bank_orgnum -- 按手机号和身份证查询较大值，近1个月在银行机构申请机构数
      ,dd.als_m1_bank_tra_orgnum -- 按手机号和身份证查询较大值，近1个月在银行机构传统银行申请机构数
      ,dd.als_m1_bank_ret_orgnum -- 按手机号和身份证查询较大值，近1个月在银行机构网络零售银行申请机构数
      ,dd.als_m1_bank_week_allnum -- 按手机号和身份证查询较大值，近1个月在银行机构周末申请次数
      ,dd.als_m1_bank_week_orgnum -- 按手机号和身份证查询较大值，近1个月在银行机构周末申请机构数
      ,dd.als_m1_bank_night_allnum -- 按手机号和身份证查询较大值，近1个月在银行机构夜间申请次数
      ,dd.als_m1_bank_night_orgnum -- 按手机号和身份证查询较大值，近1个月在银行机构夜间申请机构数
      ,dd.als_m1_nbank_selfnum -- 按手机号和身份证查询较大值，近1个月在本机构(本机构为非银)申请次数
      ,dd.als_m1_nbank_allnum -- 按手机号和身份证查询较大值，近1个月在非银机构申请次数
      ,dd.als_m1_nbank_p2p_allnum -- 按手机号和身份证查询较大值，近1个月在非银机构p2p机构申请次数
      ,dd.als_m1_nbank_mc_allnum -- 按手机号和身份证查询较大值，近1个月在非银机构小贷机构申请次数
      ,dd.als_m1_nbank_ca_allnum -- 按手机号和身份证查询较大值，近1个月在非银机构现金类分期机构申请次数
      ,dd.als_m1_nbank_cf_allnum -- 按手机号和身份证查询较大值，近1个月在非银机构消费类分期机构申请次数
      ,dd.als_m1_nbank_com_allnum -- 按手机号和身份证查询较大值，近1个月在非银机构代偿类分期机构申请次数
      ,dd.als_m1_nbank_oth_allnum -- 按手机号和身份证查询较大值，近1个月在非银机构其他申请次数
      ,dd.als_m1_nbank_nsloan_allnum -- 按手机号和身份证查询较大值，近1个月在非银机构持牌网络小贷机构申请次数
      ,dd.als_m1_nbank_autofin_allnum -- 按手机号和身份证查询较大值，近1个月在非银机构持牌汽车金融机构申请次数
      ,dd.als_m1_nbank_sloan_allnum -- 按手机号和身份证查询较大值，近1个月在非银机构持牌小贷机构申请次数
      ,dd.als_m1_nbank_cons_allnum -- 按手机号和身份证查询较大值，近1个月在非银机构持牌消费金融机构申请次数
      ,dd.als_m1_nbank_finlea_allnum -- 按手机号和身份证查询较大值，近1个月在非银机构持牌融资租赁机构申请次数
      ,dd.als_m1_nbank_else_allnum -- 按手机号和身份证查询较大值，近1个月在非银机构其他申请次数
      ,dd.als_m1_nbank_orgnum -- 按手机号和身份证查询较大值，近1个月在非银机构申请机构数
      ,dd.als_m1_nbank_p2p_orgnum -- 按手机号和身份证查询较大值，近1个月在非银机构p2p申请机构数
      ,dd.als_m1_nbank_mc_orgnum -- 按手机号和身份证查询较大值，近1个月在非银机构小贷申请机构数
      ,dd.als_m1_nbank_ca_orgnum -- 按手机号和身份证查询较大值，近1个月在非银机构现金类分期申请机构数
      ,dd.als_m1_nbank_cf_orgnum -- 按手机号和身份证查询较大值，近1个月在非银机构消费类分期申请机构数
      ,dd.als_m1_nbank_com_orgnum -- 按手机号和身份证查询较大值，近1个月在非银机构代偿类分期申请机构数
      ,dd.als_m1_nbank_oth_orgnum -- 按手机号和身份证查询较大值，近1个月在非银机构其他申请机构数
      ,dd.als_m1_nbank_nsloan_orgnum -- 按手机号和身份证查询较大值，近1个月在非银机构持牌网络小贷机构申请机构数
      ,dd.als_m1_nbank_autofin_orgnum -- 按手机号和身份证查询较大值，近1个月在非银机构持牌汽车金融机构申请机构数
      ,dd.als_m1_nbank_sloan_orgnum -- 按手机号和身份证查询较大值，近1个月在非银机构持牌小贷机构申请机构数
      ,dd.als_m1_nbank_cons_orgnum -- 按手机号和身份证查询较大值，近1个月在非银机构持牌消费金融机构申请机构数
      ,dd.als_m1_nbank_finlea_orgnum -- 按手机号和身份证查询较大值，近1个月在非银机构持牌融资租赁机构申请机构数
      ,dd.als_m1_nbank_else_orgnum -- 按手机号和身份证查询较大值，近1个月在非银机构其他申请机构数
      ,dd.als_m1_nbank_week_allnum -- 按手机号和身份证查询较大值，近1个月在非银机构周末申请次数
      ,dd.als_m1_nbank_week_orgnum -- 按手机号和身份证查询较大值，近1个月在非银机构周末申请机构数
      ,dd.als_m1_nbank_night_allnum -- 按手机号和身份证查询较大值，近1个月在非银机构夜间申请次数
      ,dd.als_m1_nbank_night_orgnum -- 按手机号和身份证查询较大值，近1个月在非银机构夜间申请机构数
      ,dd.als_m3_max_inteday -- 按手机号和身份证查询较大值，近3个月申请最大间隔天数
      ,dd.als_m3_min_inteday -- 按手机号和身份证查询较大值，近3个月申请最小间隔天数
      ,dd.als_m3_tot_mons -- 按手机号和身份证查询较大值，近3个月平均每月申请次数(有申请月份平均)
      ,dd.als_m3_avg_monnum -- 按手机号和身份证查询较大值，近3个月最大月申请次数
      ,dd.als_m3_max_monnum -- 按手机号和身份证查询较大值，近3个月最大月申请次数
      ,dd.als_m3_min_monnum -- 按手机号和身份证查询较大值，近3个月最小月申请次数
      ,dd.als_m3_pdl_allnum -- 按手机号和身份证查询较大值，近3个月申请线上小额现金贷的次数
      ,dd.als_m3_pdl_orgnum -- 按手机号和身份证查询较大值，近3个月申请线上小额现金贷的机构数
      ,dd.als_m3_caon_allnum -- 按手机号和身份证查询较大值，近3个月申请线上现金分期的次数
      ,dd.als_m3_caon_orgnum -- 按手机号和身份证查询较大值，近3个月申请线上现金分期的机构数
      ,dd.als_m3_rel_allnum -- 按手机号和身份证查询较大值，近3个月申请信用卡（类信用卡）的次数
      ,dd.als_m3_rel_orgnum -- 按手机号和身份证查询较大值，近3个月申请信用卡（类信用卡）的机构数
      ,dd.als_m3_caoff_allnum -- 按手机号和身份证查询较大值，近3个月申请线下现金分期的次数
      ,dd.als_m3_caoff_orgnum -- 按手机号和身份证查询较大值，近3个月申请线下现金分期的机构数
      ,dd.als_m3_cooff_allnum -- 按手机号和身份证查询较大值，近3个月申请线下消费分期的次数
      ,dd.als_m3_cooff_orgnum -- 按手机号和身份证查询较大值，近3个月申请线下消费分期的机构数
      ,dd.als_m3_af_allnum -- 按手机号和身份证查询较大值，近3个月申请汽车金融的次数
      ,dd.als_m3_af_orgnum -- 按手机号和身份证查询较大值，近3个月申请汽车金融的机构数
      ,dd.als_m3_coon_allnum -- 按手机号和身份证查询较大值，近3个月申请线上消费分期的次数
      ,dd.als_m3_coon_orgnum -- 按手机号和身份证查询较大值，近3个月申请线上消费分期的机构数
      ,dd.als_m3_oth_allnum -- 按手机号和身份证查询较大值，近3个月申请其他的次数
      ,dd.als_m3_oth_orgnum -- 按手机号和身份证查询较大值，近3个月申请其他的机构数
      ,dd.als_m3_bank_selfnum -- 按手机号和身份证查询较大值，近3个月在本机构(本机构为银行)的申请次数
      ,dd.als_m3_bank_allnum -- 按手机号和身份证查询较大值，近3个月在银行机构申请次数
      ,dd.als_m3_bank_tra_allnum -- 按手机号和身份证查询较大值，近3个月在银行机构传统银行申请次数
      ,dd.als_m3_bank_ret_allnum -- 按手机号和身份证查询较大值，近3个月在银行机构网络零售银行申请次数
      ,dd.als_m3_bank_orgnum -- 按手机号和身份证查询较大值，近3个月在银行机构申请机构数
      ,dd.als_m3_bank_tra_orgnum -- 按手机号和身份证查询较大值，近3个月在银行机构传统银行申请机构数
      ,dd.als_m3_bank_ret_orgnum -- 按手机号和身份证查询较大值，近3个月在银行机构网络零售银行申请机构数
      ,dd.als_m3_bank_tot_mons -- 按手机号和身份证查询较大值，近3个月在银行机构有申请记录月份数
      ,dd.als_m3_bank_avg_monnum -- 按手机号和身份证查询较大值，近3个月在银行机构平均每月申请次数(有申请月份平均)
      ,dd.als_m3_bank_max_monnum -- 按手机号和身份证查询较大值，近3个月在银行机构最大月申请次数
      ,dd.als_m3_bank_min_monnum -- 按手机号和身份证查询较大值，近3个月在银行机构最小月申请次数
      ,dd.als_m3_bank_max_inteday -- 按手机号和身份证查询较大值，近3个月在银行机构申请最大间隔天数
      ,dd.als_m3_bank_min_inteday -- 按手机号和身份证查询较大值，近3个月在银行机构申请最小间隔天数
      ,dd.als_m3_bank_week_allnum -- 按手机号和身份证查询较大值，近3个月在银行机构周末申请次数
      ,dd.als_m3_bank_week_orgnum -- 按手机号和身份证查询较大值，近3个月在银行机构周末申请机构数
      ,dd.als_m3_bank_night_allnum -- 按手机号和身份证查询较大值，近3个月在银行机构夜间申请次数
      ,dd.als_m3_bank_night_orgnum -- 按手机号和身份证查询较大值，近3个月在银行机构夜间申请机构数
      ,dd.als_m3_nbank_selfnum -- 按手机号和身份证查询较大值，近3个月在本机构(本机构为非银)申请次数
      ,dd.als_m3_nbank_allnum -- 按手机号和身份证查询较大值，近3个月在非银机构申请次数
      ,dd.als_m3_nbank_p2p_allnum -- 按手机号和身份证查询较大值，近3个月在非银机构p2p机构申请次数
      ,dd.als_m3_nbank_mc_allnum -- 按手机号和身份证查询较大值，近3个月在非银机构小贷机构申请次数
      ,dd.als_m3_nbank_ca_allnum -- 按手机号和身份证查询较大值，近3个月在非银机构现金类分期机构申请次数
      ,dd.als_m3_nbank_cf_allnum -- 按手机号和身份证查询较大值，近3个月在非银机构消费类分期机构申请次数
      ,dd.als_m3_nbank_com_allnum -- 按手机号和身份证查询较大值，近3个月在非银机构代偿类分期机构申请次数
      ,dd.als_m3_nbank_oth_allnum -- 按手机号和身份证查询较大值，近3个月在非银机构其他申请次数
      ,dd.als_m3_nbank_nsloan_allnum -- 按手机号和身份证查询较大值，近3个月在非银机构持牌网络小贷机构申请次数
      ,dd.als_m3_nbank_autofin_allnum -- 按手机号和身份证查询较大值，近3个月在非银机构持牌汽车金融机构申请次数
      ,dd.als_m3_nbank_sloan_allnum -- 按手机号和身份证查询较大值，近3个月在非银机构持牌小贷机构申请次数
      ,dd.als_m3_nbank_cons_allnum -- 按手机号和身份证查询较大值，近3个月在非银机构持牌消费金融机构申请次数
      ,dd.als_m3_nbank_finlea_allnum -- 按手机号和身份证查询较大值，近3个月在非银机构持牌融资租赁机构申请次数
      ,dd.als_m3_nbank_else_allnum -- 按手机号和身份证查询较大值，近3个月在非银机构其他申请次数
      ,dd.als_m3_nbank_orgnum -- 按手机号和身份证查询较大值，近3个月在非银机构申请机构数
      ,dd.als_m3_nbank_p2p_orgnum -- 按手机号和身份证查询较大值，近3个月在非银机构p2p申请机构数
      ,dd.als_m3_nbank_mc_orgnum -- 按手机号和身份证查询较大值，近3个月在非银机构小贷申请机构数
      ,dd.als_m3_nbank_ca_orgnum -- 按手机号和身份证查询较大值，近3个月在非银机构现金类分期申请机构数
      ,dd.als_m3_nbank_cf_orgnum -- 按手机号和身份证查询较大值，近3个月在非银机构消费类分期申请机构数
      ,dd.als_m3_nbank_com_orgnum -- 按手机号和身份证查询较大值，近3个月在非银机构代偿类分期申请机构数
      ,dd.als_m3_nbank_oth_orgnum -- 按手机号和身份证查询较大值，近3个月在非银机构其他申请机构数
      ,dd.als_m3_nbank_nsloan_orgnum -- 按手机号和身份证查询较大值，近3个月在非银机构持牌网络小贷机构申请机构数
      ,dd.als_m3_nbank_autofin_orgnum -- 按手机号和身份证查询较大值，近3个月在非银机构持牌汽车金融机构申请机构数
      ,dd.als_m3_nbank_sloan_orgnum -- 按手机号和身份证查询较大值，近3个月在非银机构持牌小贷机构申请机构数
      ,dd.als_m3_nbank_cons_orgnum -- 按手机号和身份证查询较大值，近3个月在非银机构持牌消费金融机构申请机构数
      ,dd.als_m3_nbank_finlea_orgnum -- 按手机号和身份证查询较大值，近3个月在非银机构持牌融资租赁机构申请机构数
      ,dd.als_m3_nbank_else_orgnum -- 按手机号和身份证查询较大值，近3个月在非银机构其他申请机构数
      ,dd.als_m3_nbank_tot_mons -- 按手机号和身份证查询较大值，近3个月在非银机构有申请记录月份数
      ,dd.als_m3_nbank_avg_monnum -- 按手机号和身份证查询较大值，近3个月在非银机构平均每月申请次数(有申请月份平均)
      ,dd.als_m3_nbank_max_monnum -- 按手机号和身份证查询较大值，近3个月在非银机构最大月申请次数
      ,dd.als_m3_nbank_min_monnum -- 按手机号和身份证查询较大值，近3个月在非银机构最小月申请次数
      ,dd.als_m3_nbank_max_inteday -- 按手机号和身份证查询较大值，近3个月在非银机构申请最大间隔天数
      ,dd.als_m3_nbank_min_inteday -- 按手机号和身份证查询较大值，近3个月在非银机构申请最小间隔天数
      ,dd.als_m3_nbank_week_allnum -- 按手机号和身份证查询较大值，近3个月在非银机构周末申请次数
      ,dd.als_m3_nbank_week_orgnum -- 按手机号和身份证查询较大值，近3个月在非银机构周末申请机构数
      ,dd.als_m3_nbank_night_allnum -- 按手机号和身份证查询较大值，近3个月在非银机构夜间申请次数
      ,dd.als_m3_nbank_night_orgnum -- 按手机号和身份证查询较大值，近3个月在非银机构夜间申请机构数
      ,dd.als_m6_max_inteday -- 按手机号和身份证查询较大值，近6个月申请最大间隔天数
      ,dd.als_m6_min_inteday -- 按手机号和身份证查询较大值，近6个月申请最小间隔天数
      ,dd.als_m6_tot_mons -- 按手机号和身份证查询较大值，近6个月有申请记录月份数
      ,dd.als_m6_avg_monnum -- 按手机号和身份证查询较大值，近6个月平均每月申请次数(有申请月份平均)
      ,dd.als_m6_max_monnum -- 按手机号和身份证查询较大值，近6个月最大月申请次数
      ,dd.als_m6_min_monnum -- 按手机号和身份证查询较大值，近6个月最小月申请次数
      ,dd.als_m6_pdl_allnum -- 按手机号和身份证查询较大值，近6个月申请线上小额现金贷的次数
      ,dd.als_m6_pdl_orgnum -- 按手机号和身份证查询较大值，近6个月申请线上小额现金贷的机构数
      ,dd.als_m6_caon_allnum -- 按手机号和身份证查询较大值，近6个月申请线上现金分期的次数
      ,dd.als_m6_caon_orgnum -- 按手机号和身份证查询较大值，近6个月申请线上现金分期的机构数
      ,dd.als_m6_rel_allnum -- 按手机号和身份证查询较大值，近6个月申请信用卡（类信用卡）的次数
      ,dd.als_m6_rel_orgnum -- 按手机号和身份证查询较大值，近6个月申请信用卡（类信用卡）的机构数
      ,dd.als_m6_caoff_allnum -- 按手机号和身份证查询较大值，近6个月申请线下现金分期的次数
      ,dd.als_m6_caoff_orgnum -- 按手机号和身份证查询较大值，近6个月申请线下现金分期的机构数
      ,dd.als_m6_cooff_allnum -- 按手机号和身份证查询较大值，近6个月申请线下消费分期的次数
      ,dd.als_m6_cooff_orgnum -- 按手机号和身份证查询较大值，近6个月申请线下消费分期的机构数
      ,dd.als_m6_af_allnum -- 按手机号和身份证查询较大值，近6个月申请汽车金融的次数
      ,dd.als_m6_af_orgnum -- 按手机号和身份证查询较大值，近6个月申请汽车金融的机构数
      ,dd.als_m6_coon_allnum -- 按手机号和身份证查询较大值，近6个月申请线上消费分期的次数
      ,dd.als_m6_coon_orgnum -- 按手机号和身份证查询较大值，近6个月申请线上消费分期的机构数
      ,dd.als_m6_oth_allnum -- 按手机号和身份证查询较大值，近6个月申请其他的次数
      ,dd.als_m6_oth_orgnum -- 按手机号和身份证查询较大值，近6个月申请其他的机构数
      ,dd.als_m6_bank_selfnum -- 按手机号和身份证查询较大值，近6个月在本机构(本机构为银行)的申请次数
      ,dd.als_m6_bank_allnum -- 按手机号和身份证查询较大值，近6个月在银行机构申请次数
      ,dd.als_m6_bank_tra_allnum -- 按手机号和身份证查询较大值，近6个月在银行机构传统银行申请次数
      ,dd.als_m6_bank_ret_allnum -- 按手机号和身份证查询较大值，近6个月在银行机构网络零售银行申请次数
      ,dd.als_m6_bank_orgnum -- 按手机号和身份证查询较大值，近6个月在银行机构申请机构数
      ,dd.als_m6_bank_tra_orgnum -- 按手机号和身份证查询较大值，近6个月在银行机构传统银行申请机构数
      ,dd.als_m6_bank_ret_orgnum -- 按手机号和身份证查询较大值，近6个月在银行机构网络零售银行申请机构数
      ,dd.als_m6_bank_tot_mons -- 按手机号和身份证查询较大值，近6个月在银行机构有申请记录月份数
      ,dd.als_m6_bank_avg_monnum -- 按手机号和身份证查询较大值，近6个月在银行机构平均每月申请次数(有申请月份平均)
      ,dd.als_m6_bank_max_monnum -- 按手机号和身份证查询较大值，近6个月在银行机构最大月申请次数
      ,dd.als_m6_bank_min_monnum -- 按手机号和身份证查询较大值，近6个月在银行机构最小月申请次数
      ,dd.als_m6_bank_max_inteday -- 按手机号和身份证查询较大值，近6个月在银行机构申请最大间隔天数
      ,dd.als_m6_bank_min_inteday -- 按手机号和身份证查询较大值，近6个月在银行机构申请最小间隔天数
      ,dd.als_m6_bank_week_allnum -- 按手机号和身份证查询较大值，近6个月在银行机构周末申请次数
      ,dd.als_m6_bank_week_orgnum -- 按手机号和身份证查询较大值，近6个月在银行机构周末申请机构数
      ,dd.als_m6_bank_night_allnum -- 按手机号和身份证查询较大值，近6个月在银行机构夜间申请次数
      ,dd.als_m6_bank_night_orgnum -- 按手机号和身份证查询较大值，近6个月在银行机构夜间申请机构数
      ,dd.als_m6_nbank_selfnum -- 按手机号和身份证查询较大值，近6个月在本机构(本机构为非银)申请次数
      ,dd.als_m6_nbank_allnum -- 按手机号和身份证查询较大值，近6个月在非银机构申请次数
      ,dd.als_m6_nbank_p2p_allnum -- 按手机号和身份证查询较大值，近6个月在非银机构p2p机构申请次数
      ,dd.als_m6_nbank_mc_allnum -- 按手机号和身份证查询较大值，近6个月在非银机构小贷机构申请次数
      ,dd.als_m6_nbank_ca_allnum -- 按手机号和身份证查询较大值，近6个月在非银机构现金类分期机构申请次数
      ,dd.als_m6_nbank_cf_allnum -- 按手机号和身份证查询较大值，近6个月在非银机构消费类分期机构申请次数
      ,dd.als_m6_nbank_com_allnum -- 按手机号和身份证查询较大值，近6个月在非银机构代偿类分期机构申请次数
      ,dd.als_m6_nbank_oth_allnum -- 按手机号和身份证查询较大值，近6个月在非银机构其他申请次数
      ,dd.als_m6_nbank_nsloan_allnum -- 按手机号和身份证查询较大值，近6个月在非银机构持牌网络小贷机构申请次数
      ,dd.als_m6_nbank_autofin_allnum -- 按手机号和身份证查询较大值，近6个月在非银机构持牌汽车金融机构申请次数
      ,dd.als_m6_nbank_sloan_allnum -- 按手机号和身份证查询较大值，近6个月在非银机构持牌小贷机构申请次数
      ,dd.als_m6_nbank_cons_allnum -- 按手机号和身份证查询较大值，近6个月在非银机构持牌消费金融机构申请次数
      ,dd.als_m6_nbank_finlea_allnum -- 按手机号和身份证查询较大值，近6个月在非银机构持牌融资租赁机构申请次数
      ,dd.als_m6_nbank_else_allnum -- 按手机号和身份证查询较大值，近6个月在非银机构其他申请次数
      ,dd.als_m6_nbank_orgnum -- 按手机号和身份证查询较大值，近6个月在非银机构申请机构数
      ,dd.als_m6_nbank_p2p_orgnum -- 按手机号和身份证查询较大值，近6个月在非银机构p2p申请机构数
      ,dd.als_m6_nbank_mc_orgnum -- 按手机号和身份证查询较大值，近6个月在非银机构小贷申请机构数
      ,dd.als_m6_nbank_ca_orgnum -- 按手机号和身份证查询较大值，近6个月在非银机构现金类分期申请机构数
      ,dd.als_m6_nbank_cf_orgnum -- 按手机号和身份证查询较大值，近6个月在非银机构消费类分期申请机构数
      ,dd.als_m6_nbank_com_orgnum -- 按手机号和身份证查询较大值，近6个月在非银机构代偿类分期申请机构数
      ,dd.als_m6_nbank_oth_orgnum -- 按手机号和身份证查询较大值，近6个月在非银机构其他申请机构数
      ,dd.als_m6_nbank_nsloan_orgnum -- 按手机号和身份证查询较大值，近6个月在非银机构持牌网络小贷机构申请机构数
      ,dd.als_m6_nbank_autofin_orgnum -- 按手机号和身份证查询较大值，近6个月在非银机构持牌汽车金融机构申请机构数
      ,dd.als_m6_nbank_sloan_orgnum -- 按手机号和身份证查询较大值，近6个月在非银机构持牌小贷机构申请机构数
      ,dd.als_m6_nbank_cons_orgnum -- 按手机号和身份证查询较大值，近6个月在非银机构持牌消费金融机构申请机构数
      ,dd.als_m6_nbank_finlea_orgnum -- 按手机号和身份证查询较大值，近6个月在非银机构持牌融资租赁机构申请机构数
      ,dd.als_m6_nbank_else_orgnum -- 按手机号和身份证查询较大值，近6个月在非银机构其他申请机构数
      ,dd.als_m6_nbank_tot_mons -- 按手机号和身份证查询较大值，近6个月在非银机构有申请记录月份数
      ,dd.als_m6_nbank_avg_monnum -- 按手机号和身份证查询较大值，近6个月在非银机构平均每月申请次数(有申请月份平均)
      ,dd.als_m6_nbank_max_monnum -- 按手机号和身份证查询较大值，近6个月在非银机构最大月申请次数
      ,dd.als_m6_nbank_min_monnum -- 按手机号和身份证查询较大值，近6个月在非银机构最小月申请次数
      ,dd.als_m6_nbank_max_inteday -- 按手机号和身份证查询较大值，近6个月在非银机构申请最大间隔天数
      ,dd.als_m6_nbank_min_inteday -- 按手机号和身份证查询较大值，近6个月在非银机构申请最小间隔天数
      ,dd.als_m6_nbank_week_allnum -- 按手机号和身份证查询较大值，近6个月在非银机构周末申请次数
      ,dd.als_m6_nbank_week_orgnum -- 按手机号和身份证查询较大值，近6个月在非银机构周末申请机构数
      ,dd.als_m6_nbank_night_allnum -- 按手机号和身份证查询较大值，近6个月在非银机构夜间申请次数
      ,dd.als_m6_nbank_night_orgnum -- 按手机号和身份证查询较大值，近6个月在非银机构夜间申请机构数
      ,dd.als_m12_max_inteday -- 按手机号和身份证查询较大值，近12个月申请最大间隔天数
      ,dd.als_m12_min_inteday -- 按手机号和身份证查询较大值，近12个月申请最小间隔天数
      ,dd.als_m12_tot_mons -- 按手机号和身份证查询较大值，近12个月有申请记录月份数
      ,dd.als_m12_avg_monnum -- 按手机号和身份证查询较大值，近12个月平均每月申请次数(有申请月份平均)
      ,dd.als_m12_max_monnum -- 按手机号和身份证查询较大值，近12个月最大月申请次数
      ,dd.als_m12_min_monnum -- 按手机号和身份证查询较大值，近12个月最小月申请次数
      ,dd.als_m12_pdl_allnum -- 按手机号和身份证查询较大值，近12个月申请线上小额现金贷的次数
      ,dd.als_m12_pdl_orgnum -- 按手机号和身份证查询较大值，近12个月申请线上小额现金贷的机构数
      ,dd.als_m12_caon_allnum -- 按手机号和身份证查询较大值，近12个月申请线上现金分期的次数
      ,dd.als_m12_caon_orgnum -- 按手机号和身份证查询较大值，近12个月申请线上现金分期的机构数
      ,dd.als_m12_rel_allnum -- 按手机号和身份证查询较大值，近12个月申请信用卡（类信用卡）的次数
      ,dd.als_m12_rel_orgnum -- 按手机号和身份证查询较大值，近12个月申请信用卡（类信用卡）的机构数
      ,dd.als_m12_caoff_allnum -- 按手机号和身份证查询较大值，近12个月申请线下现金分期的次数
      ,dd.als_m12_caoff_orgnum -- 按手机号和身份证查询较大值，近12个月申请线下现金分期的机构数
      ,dd.als_m12_cooff_allnum -- 按手机号和身份证查询较大值，近12个月申请线下消费分期的次数
      ,dd.als_m12_cooff_orgnum -- 按手机号和身份证查询较大值，近12个月申请线下消费分期的机构数
      ,dd.als_m12_af_allnum -- 按手机号和身份证查询较大值，近12个月申请汽车金融的次数
      ,dd.als_m12_af_orgnum -- 按手机号和身份证查询较大值，近12个月申请汽车金融的机构数
      ,dd.als_m12_coon_allnum -- 按手机号和身份证查询较大值，近12个月申请线上消费分期的次数
      ,dd.als_m12_coon_orgnum -- 按手机号和身份证查询较大值，近12个月申请线上消费分期的机构数
      ,dd.als_m12_oth_allnum -- 按手机号和身份证查询较大值，近12个月申请其他的次数
      ,dd.als_m12_oth_orgnum -- 按手机号和身份证查询较大值，近12个月申请其他的机构数
      ,dd.als_m12_bank_selfnum -- 按手机号和身份证查询较大值，近12个月在本机构(本机构为银行)的申请次数
      ,dd.als_m12_bank_allnum -- 按手机号和身份证查询较大值，近12个月在银行机构申请次数
      ,dd.als_m12_bank_tra_allnum -- 按手机号和身份证查询较大值，近12个月在银行机构传统银行申请次数
      ,dd.als_m12_bank_ret_allnum -- 按手机号和身份证查询较大值，近12个月在银行机构网络零售银行申请次数
      ,dd.als_m12_bank_orgnum -- 按手机号和身份证查询较大值，近12个月在银行机构申请机构数
      ,dd.als_m12_bank_tra_orgnum -- 按手机号和身份证查询较大值，近12个月在银行机构传统银行申请机构数
      ,dd.als_m12_bank_ret_orgnum -- 按手机号和身份证查询较大值，近12个月在银行机构网络零售银行申请机构数
      ,dd.als_m12_bank_tot_mons -- 按手机号和身份证查询较大值，近12个月在银行机构有申请记录月份数
      ,dd.als_m12_bank_avg_monnum -- 按手机号和身份证查询较大值，近12个月在银行机构平均每月申请次数(有申请月份平均)
      ,dd.als_m12_bank_max_monnum -- 按手机号和身份证查询较大值，近12个月在银行机构最大月申请次数
      ,dd.als_m12_bank_min_monnum -- 按手机号和身份证查询较大值，近12个月在银行机构最小月申请次数
      ,dd.als_m12_bank_max_inteday -- 按手机号和身份证查询较大值，近12个月在银行机构申请最大间隔天数
      ,dd.als_m12_bank_min_inteday -- 按手机号和身份证查询较大值，近12个月在银行机构申请最小间隔天数
      ,dd.als_m12_bank_week_allnum -- 按手机号和身份证查询较大值，近12个月在银行机构周末申请次数
      ,dd.als_m12_bank_week_orgnum -- 按手机号和身份证查询较大值，近12个月在银行机构周末申请机构数
      ,dd.als_m12_bank_night_allnum -- 按手机号和身份证查询较大值，近12个月在银行机构夜间申请次数
      ,dd.als_m12_bank_night_orgnum -- 按手机号和身份证查询较大值，近12个月在银行机构夜间申请机构数
      ,dd.als_m12_nbank_selfnum -- 按手机号和身份证查询较大值，近12个月在本机构(本机构为非银)申请次数
      ,dd.als_m12_nbank_allnum -- 按手机号和身份证查询较大值，近12个月在非银机构申请次数
      ,dd.als_m12_nbank_p2p_allnum -- 按手机号和身份证查询较大值，近12个月在非银机构p2p机构申请次数
      ,dd.als_m12_nbank_mc_allnum -- 按手机号和身份证查询较大值，近12个月在非银机构小贷机构申请次数
      ,dd.als_m12_nbank_ca_allnum -- 按手机号和身份证查询较大值，近12个月在非银机构现金类分期机构申请次数
      ,dd.als_m12_nbank_cf_allnum -- 按手机号和身份证查询较大值，近12个月在非银机构消费类分期机构申请次数
      ,dd.als_m12_nbank_com_allnum -- 按手机号和身份证查询较大值，近12个月在非银机构代偿类分期机构申请次数
      ,dd.als_m12_nbank_oth_allnum -- 按手机号和身份证查询较大值，近12个月在非银机构其他申请次数
      ,dd.als_m12_nbank_nsloan_allnum -- 按手机号和身份证查询较大值，近12个月在非银机构持牌网络小贷机构申请次数
      ,dd.als_m12_nbank_autofin_allnum -- 按手机号和身份证查询较大值，近12个月在非银机构持牌汽车金融机构申请次数
      ,dd.als_m12_nbank_sloan_allnum -- 按手机号和身份证查询较大值，近12个月在非银机构持牌小贷机构申请次数
      ,dd.als_m12_nbank_cons_allnum -- 按手机号和身份证查询较大值，近12个月在非银机构持牌消费金融机构申请次数
      ,dd.als_m12_nbank_finlea_allnum -- 按手机号和身份证查询较大值，近12个月在非银机构持牌融资租赁机构申请次数
      ,dd.als_m12_nbank_else_allnum -- 按手机号和身份证查询较大值，近12个月在非银机构其他申请次数
      ,dd.als_m12_nbank_orgnum -- 按手机号和身份证查询较大值，近12个月在非银机构申请机构数
      ,dd.als_m12_nbank_p2p_orgnum -- 按手机号和身份证查询较大值，近12个月在非银机构p2p申请机构数
      ,dd.als_m12_nbank_mc_orgnum -- 按手机号和身份证查询较大值，近12个月在非银机构小贷申请机构数
      ,dd.als_m12_nbank_ca_orgnum -- 按手机号和身份证查询较大值，近12个月在非银机构现金类分期申请机构数
      ,dd.als_m12_nbank_cf_orgnum -- 按手机号和身份证查询较大值，近12个月在非银机构消费类分期申请机构数
      ,dd.als_m12_nbank_com_orgnum -- 按手机号和身份证查询较大值，近12个月在非银机构代偿类分期申请机构数
      ,dd.als_m12_nbank_oth_orgnum -- 按手机号和身份证查询较大值，近12个月在非银机构其他申请机构数
      ,dd.als_m12_nbank_nsloan_orgnum -- 按手机号和身份证查询较大值，近12个月在非银机构持牌网络小贷机构申请机构数
      ,dd.als_m12_nbank_autofin_orgnum -- 按手机号和身份证查询较大值，近12个月在非银机构持牌汽车金融机构申请机构数
      ,dd.als_m12_nbank_sloan_orgnum -- 按手机号和身份证查询较大值，近12个月在非银机构持牌小贷机构申请机构数
      ,dd.als_m12_nbank_cons_orgnum -- 按手机号和身份证查询较大值，近12个月在非银机构持牌消费金融机构申请机构数
      ,dd.als_m12_nbank_finlea_orgnum -- 按手机号和身份证查询较大值，近12个月在非银机构持牌融资租赁机构申请机构数
      ,dd.als_m12_nbank_else_orgnum -- 按手机号和身份证查询较大值，近12个月在非银机构其他申请机构数
      ,dd.als_m12_nbank_tot_mons -- 按手机号和身份证查询较大值，近12个月在非银机构有申请记录月份数
      ,dd.als_m12_nbank_avg_monnum -- 按手机号和身份证查询较大值，近12个月在非银机构平均每月申请次数(有申请月份平均)
      ,dd.als_m12_nbank_max_monnum -- 按手机号和身份证查询较大值，近12个月在非银机构最大月申请次数
      ,dd.als_m12_nbank_min_monnum -- 按手机号和身份证查询较大值，近12个月在非银机构最小月申请次数
      ,dd.als_m12_nbank_max_inteday -- 按手机号和身份证查询较大值，近12个月在非银机构申请最大间隔天数
      ,dd.als_m12_nbank_min_inteday -- 按手机号和身份证查询较大值，近12个月在非银机构申请最小间隔天数
      ,dd.als_m12_nbank_week_allnum -- 按手机号和身份证查询较大值，近12个月在非银机构周末申请次数
      ,dd.als_m12_nbank_week_orgnum -- 按手机号和身份证查询较大值，近12个月在非银机构周末申请机构数
      ,dd.als_m12_nbank_night_allnum -- 按手机号和身份证查询较大值，近12个月在非银机构夜间申请次数
      ,dd.als_m12_nbank_night_orgnum -- 按手机号和身份证查询较大值，近12个月在非银机构夜间申请机构数
      ,dd.als_fst_bank_inteday -- 按手机号和身份证查询较大值，距最早在银行机构申请的间隔天数
      ,dd.als_fst_nbank_inteday -- 按手机号和身份证查询较大值，距最早在非银机构申请的间隔天数
      ,dd.als_lst_bank_inteday -- 按手机号和身份证查询较大值，距最近在银行机构申请的间隔天数
      ,dd.als_lst_bank_consnum -- 按手机号和身份证查询较大值，最近开始在银行机构连续申请的次数
      ,dd.als_lst_bank_csinteday -- 按手机号和身份证查询较大值，最近开始在银行机构连续申请的持续天数
      ,dd.als_lst_nbank_inteday -- 按手机号和身份证查询较大值，距最近在非银机构申请的间隔天数
      ,dd.als_lst_nbank_consnum -- 按手机号和身份证查询较大值，最近开始在非银机构连续申请的次数
      ,dd.als_lst_nbank_csinteday -- 按手机号和身份证查询较大值，最近开始在非银机构连续申请的持续天数
      ,ee.xy_a22160001 -- 申请准入分
      ,ee.xy_a22160002 -- 申请准入置信度
      ,ee.xy_a22160003 -- 申请命中机构数
      ,ee.xy_a22160004 -- 申请命中消金类机构数
      ,ee.xy_a22160005 -- 申请命中网络贷款类机构数
      ,ee.xy_a22160006 -- 机构总查询次数
      ,ee.xy_a22160007 -- 最近一次查询时间
      ,ee.xy_a22160008 -- 近1个月机构总查询笔数
      ,ee.xy_a22160009 -- 近3个月机构总查询笔数
      ,ee.xy_a22160010 -- 近6个月机构总查询笔数
      ,ee.xy_c22180001 -- 网贷授信额度
      ,ee.xy_c22180002 -- 网贷额度置信度
      ,ee.xy_c22180003 -- 网络贷款类机构数
      ,ee.xy_c22180004 -- 网络贷款类产品数
      ,ee.xy_c22180005 -- 网络贷款机构最大授信额度
      ,ee.xy_c22180006 -- 网络贷款机构平均授信额度
      ,ee.xy_c22180007 -- 消金建议授信额度
      ,ee.xy_c22180008 -- 消金额度置信度
      ,ee.xy_c22180009 -- 消金贷款类机构数
      ,ee.xy_c22180010 -- 消金贷款类产品数
      ,ee.xy_c22180011 -- 消金贷款类机构最大授信额度
      ,ee.xy_c22180012 -- 消金贷款类机构平均授信额度
      ,ee.xy_b22170002 -- 近1个月贷款笔数
      ,ee.xy_b22170003 -- 近3个月贷款笔数
      ,ee.xy_b22170004 -- 近6个月贷款笔数
      ,ee.xy_b22170005 -- 近12个月贷款笔数
      ,ee.xy_b22170006 -- 近24个月贷款笔数
      ,ee.xy_b22170007 -- 近1个月贷款总金额
      ,ee.xy_b22170008 -- 近3个月贷款总金额
      ,ee.xy_b22170009 -- 近6个月贷款总金额
      ,ee.xy_b22170010 -- 近12个月贷款总金额
      ,ee.xy_b22170011 -- 近24个月贷款总金额
      ,ee.xy_b22170012 -- 近12个月贷款金额在1k及以下的笔数
      ,ee.xy_b22170013 -- 近12个月贷款金额在1k-3k的笔数
      ,ee.xy_b22170014 -- 近12个月贷款金额在3k-10k的笔数
      ,ee.xy_b22170015 -- 近12个月贷款金额在1w以上的笔数
      ,ee.xy_b22170016 -- 近1个月贷款机构数
      ,ee.xy_b22170017 -- 近3个月贷款机构数
      ,ee.xy_b22170018 -- 近6个月贷款机构数
      ,ee.xy_b22170019 -- 近12个月贷款机构数
      ,ee.xy_b22170020 -- 近24个月贷款机构数
      ,ee.xy_b22170021 -- 近12个月消金类贷款机构数
      ,ee.xy_b22170022 -- 近24个月消金类贷款机构数
      ,ee.xy_b22170023 -- 近12个月网贷类贷款机构数
      ,ee.xy_b22170024 -- 近24个月网贷类贷款机构数
      ,ee.xy_b22170025 -- 近6个月M0+逾期贷款笔数
      ,ee.xy_b22170026 -- 近12个月M0+逾期贷款笔数
      ,ee.xy_b22170027 -- 近24个月M0+逾期贷款笔数
      ,ee.xy_b22170028 -- 近6个月M1+逾期贷款笔数
      ,ee.xy_b22170029 -- 近12个月M1+逾期贷款笔数
      ,ee.xy_b22170030 -- 近24个月M1+逾期贷款笔数
      ,ee.xy_b22170031 -- 近6个月累计逾期金额
      ,ee.xy_b22170032 -- 近12个月累计逾期金额
      ,ee.xy_b22170033 -- 近24个月累计逾期金额
      ,ee.xy_b22170034 -- 正常还款订单数占贷款总订单数比例
      ,ee.xy_b22170035 -- 近1个月失败扣款笔数
      ,ee.xy_b22170036 -- 近3个月失败扣款笔数
      ,ee.xy_b22170037 -- 近6个月失败扣款笔数
      ,ee.xy_b22170038 -- 近12个月失败扣款笔数
      ,ee.xy_b22170039 -- 近24个月失败扣款笔数
      ,ee.xy_b22170040 -- 近1个月履约贷款总金额
      ,ee.xy_b22170041 -- 近3个月履约贷款总金额
      ,ee.xy_b22170042 -- 近6个月履约贷款总金额
      ,ee.xy_b22170043 -- 近12个月履约贷款总金额
      ,ee.xy_b22170044 -- 近24个月履约贷款总金额
      ,ee.xy_b22170045 -- 近1个月履约贷款次数
      ,ee.xy_b22170046 -- 近3个月履约贷款次数
      ,ee.xy_b22170047 -- 近6个月履约贷款次数
      ,ee.xy_b22170048 -- 近12个月履约贷款次数
      ,ee.xy_b22170049 -- 近24个月履约贷款次数
      ,ee.xy_b22170050 -- 最近一次履约距今天数
      ,ee.xy_b22170051 -- 贷款行为置信度
      ,ee.xy_b22170052 -- 贷款已结清订单数
      ,ee.xy_b22170053 -- 信用贷款时长
      ,ee.xy_b22170054 -- 最近一次贷款放款时间
      ,ff.bj_top7d  --  近7天大众app活跃度
      ,ff.bj_property7d  --  近7天房产相关活跃度
      ,ff.bj_tools7d  --  近7天工具活跃度
      ,ff.bj_health7d  --  近7天健康养生活跃度
      ,ff.bj_education7d  --  近7天教育相关活跃度
      ,ff.bj_finance7d  --  近7天金融理财活跃度
      ,ff.bj_travel7d  --  近7天旅游出行活跃度
      ,ff.bj_woman7d  --  近7天女性相关活跃度
      ,ff.bj_car7d  --  近7天汽车相关活跃度
      ,ff.bj_app_stability7d  --  近7天设备总体活跃度
      ,ff.bj_sns7d  --  近7天社交活跃度
      ,ff.bj_service7d  --  近7天生活服务活跃度
      ,ff.bj_shopping7d  --  近7天网购活跃度
      ,ff.bj_tail7d  --  近7天小众app活跃度
      ,ff.bj_loan7d  --  近7天信贷活跃度
      ,ff.bj_game7d  --  近7天游戏活跃度
      ,ff.bj_entertainment7d  --  近7天娱乐活跃度
      ,ff.bj_top90d  --  近90天大众app活跃度
      ,ff.bj_property90d  --  近90天房产相关活跃度
      ,ff.bj_tools90d  --  近90天工具活跃度
      ,ff.bj_health90d  --  近90天健康养生活跃度
      ,ff.bj_education90d  --  近90天教育相关活跃度
      ,ff.bj_finance90d  --  近90天金融理财活跃度
      ,ff.bj_travel90d  --  近90天旅游出行活跃度
      ,ff.bj_woman90d  --  近90天女性相关活跃度
      ,ff.bj_car90d  --  近90天汽车相关活跃度
      ,ff.bj_app_stability90d  --  近90天设备总体活跃度
      ,ff.bj_sns90d  --  近90天社交活跃度
      ,ff.bj_service90d  --  近90天生活服务活跃度
      ,ff.bj_shopping90d  --  近90天网购活跃度
      ,ff.bj_tail90d  --  近90天小众app活跃度
      ,ff.bj_loan90d  --  近90天信贷活跃度
      ,ff.bj_game90d  --  近90天游戏活跃度
      ,ff.bj_entertainment90d  --  近90天娱乐活跃度
      ,ff.bj_reading90d  --  近90天阅读活跃度
      ,ff.bj_top180d  --  近180天大众app活跃度
      ,ff.bj_property180d  --  近180天房产相关活跃度
      ,ff.bj_tools180d  --  近180天工具活跃度
      ,ff.bj_health180d  --  近180天健康养生活跃度
      ,ff.bj_education180d  --  近180天教育相关活跃度
      ,ff.bj_finance180d  --  近180天金融理财活跃度
      ,ff.bj_travel180d  --  近180天旅游出行活跃度
      ,ff.bj_woman180d  --  近180天女性相关活跃度
      ,ff.bj_car180d  --  近180天汽车相关活跃度
      ,ff.bj_app_stability180d  --  近180天设备总体活跃度
      ,ff.bj_sns180d  --  近180天社交活跃度
      ,ff.bj_service180d  --  近180天生活服务活跃度
      ,ff.bj_shopping180d  --  近180天网购活跃度
      ,ff.bj_tail180d  --  近180天小众app活跃度
      ,ff.bj_loan180d  --  近180天信贷活跃度
      ,ff.bj_game180d  --  近180天游戏活跃度
      ,ff.bj_entertainment180d  --  近180天娱乐活跃度
      ,ff.bj_reading7d  --  近180天阅读活跃度
      ,ff.bj_reading180d  --  近180天阅读活跃度
      ,gg.br_alf_apirisk_d180_mean -- 最近180天申请的申请机构风险等级均值
      ,gg.br_alf_apirisk_d180_sum -- 最近180天申请的申请机构风险等级求和
      ,gg.br_alf_apirisk_d30_sum -- 最近30天申请的申请机构风险等级求和
      ,gg.br_alf_apirisk_d90_sum -- 最近90天申请的申请机构风险等级求和
      ,gg.br_alf_apirisk_time_area_d15_sum -- 最近15天申请的申请机构风险相邻算法取值的求和
      ,gg.br_alf_apirisk_time_area_d180_mean -- 最近180天申请的申请机构风险相邻算法取值的均值
      ,gg.br_alf_apirisk_time_area_d30_sum -- 最近30天申请的申请机构风险相邻算法取值的求和
      ,gg.br_alf_apirisk_time_area_d360_mean -- 最近360天申请的申请机构风险相邻算法取值的均值
      ,gg.br_alf_apirisk_time_area_d90_mean -- 最近90天申请的申请机构风险相邻算法取值的均值
      ,gg.br_alf_apirisk_time_area_d90_sum -- 最近90天申请的申请机构风险相邻算法取值的求和
      ,gg.br_alf_apirisk_time_slope_d360_mean -- 最近360天申请的申请机构风险趋势算法取值的均值
      ,gg.br_alf_count_cell_model -- 过往全部申请的不同手机号个数
      ,gg.br_alf_diff_bus_model -- 过往全部申请的不同业务类目数
      ,gg.br_als_d15_on_pro_a -- 近15天在线上申请占银行+非银申请次数的比例
      ,gg.br_als_d15_on_pro_o -- 近15天在线上申请占银行+非银申请机构数的比例
      ,gg.br_als_m1_on_pro_a -- 近1个月在线上申请占银行+非银申请次数的比例
      ,gg.br_als_m1_on_pro_o -- 近1个月在线上申请占银行+非银申请机构数的比例
      ,gg.br_als_m6_bn_o -- 近6个月占银行+非银申请机构数
      ,gg.br_cf_cons_c10_amount_model -- 近两年家居家纺类消费总金额
      ,gg.br_cf_cons_c10_views -- 近两年家居家纺类浏览总次数
      ,gg.br_cf_cons_c13_nums_model -- 近两年美食特产类购买总次数
      ,gg.br_cf_cons_c13_views -- 近两年美食特产类浏览总次数
      ,gg.br_cf_cons_c15_amount_model -- 近两年汽车用品类消费总金额
      ,gg.br_cf_cons_c15_views -- 近两年汽车用品类浏览总次数
      ,gg.br_cf_cons_c16_views -- 近两年其他类浏览总次数
      ,gg.br_cf_cons_c18_views -- 近两年收藏类浏览总次数
      ,gg.br_cf_cons_c19_views -- 近两年手机/手机配件类浏览总次数
      ,gg.br_cf_cons_c1_amount -- 近两年本地生活类消费总金额
      ,gg.br_cf_cons_c1_nums -- 近两年本地生活类购买总次数
      ,gg.br_cf_cons_c1_views -- 近两年本地生活类浏览总次数
      ,gg.br_cf_cons_c20_views -- 近两年数码类浏览总次数
      ,gg.br_cf_cons_c21_views -- 近两年通讯类浏览总次数
      ,gg.br_cf_cons_c22_views -- 近两年文化娱乐类浏览总次数
      ,gg.br_cf_cons_c25_views -- 近两年箱包类浏览总次数
      ,gg.br_cf_cons_c27_views -- 近两年医疗保健类浏览总次数
      ,gg.br_cf_cons_c29_views -- 近两年钟表首饰类浏览总次数
      ,gg.br_cf_cons_c3_views -- 近两年出差旅游类浏览总次数
      ,gg.br_cf_cons_c4_amount -- 近两年宠物生活类消费总金额
      ,gg.br_cf_cons_c4_nums -- 近两年宠物生活类购买总次数
      ,gg.br_cf_cons_c4_views -- 近两年宠物生活类浏览总次数
      ,gg.br_cf_cons_c5_views -- 近两年电脑/办公类浏览总次数
      ,gg.br_cf_cons_c8_views -- 近两年个护化妆类浏览总次数
      ,gg.br_cf_cons_views_model -- 近两年浏览总次数
      ,gg.br_cf_prob_min_model -- 请求id与cells的最小置信度
      ,gg.br_cons_m3_myyp_num -- 近3个月母婴用品类商品总消费等级
      ,gg.br_frg_list_level_model -- 查询人欺诈团伙等级
      ,gg.br_gl_m1_max_time_model -- 近1个月命中灰名单最大时间间隔
      ,gg.br_ir_allmatch_days -- 身份证和手机号完全匹配的最近查询距今天数
      ,gg.br_ir_id_x_mail_cnt -- 身份证关联的邮箱个数
      ,gg.br_ir_m12_id_x_cell_cnt -- 近12月身份证关联手机号个数
      ,gg.br_ns_avg_amt_model -- 月均消费评分
      ,gg.br_stab_mail_num_model -- 关联电子邮箱个数
      ,gg.br_tl_nowamount -- 近12个月在非银机构借贷等级
      ,zz.zhi_xin_scr -- 同盾智信分
      ,zz.br_scr -- 百融贷前联合建模分
      ,zz.bj_hm_score_v18 -- 冰鉴火眸分V18
      ,zz.tx_risk_score -- 天御反欺诈通用分
      ,zz.ali_xxhf_scr -- 阿里云先享后付分
      ,zz.zhi_shu_grd -- 智数收入等级
      ,zz.min_income -- 收入最小值
      ,zz.max_income -- 收入最大值
      ,zz.xy_b22170001 -- 贷款行为分
from default.szy_djte_dz_model_user_list as aa 
left join default.szy_djte_dz_model_user_list_basic as bb 
on aa.uid = bb.uid
left join default.szy_djte_dz_model_user_list_tnd_risk_ratio_3 as cc 
on aa.uid = cc.uid
left join default.szy_djte_dz_model_user_list_br_fst as dd
on aa.uid = dd.uid
left join default.szy_djte_dz_model_user_list_xy_dt as ee 
on aa.uid = ee.uid
left join default.szy_djte_dz_model_user_list_bj_hm as ff
on aa.uid = ff.uid
left join default.szy_djte_dz_model_user_list_br_mdl_var as gg 
on aa.uid = gg.uid
left join default.szy_djte_dz_model_user_list_wbzx_scr as zz
on aa.uid = zz.uid

